services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  dev-container:  ## for vscode dev container extension
    image: mcr.microsoft.com/devcontainers/javascript-node:24
    working_dir: /app/
    ports:
      - "5173:5173"
    volumes:
      - ../:/app:cached
      - ../dist/:/app/dist:delegated
      - dependencies:/app/node_modules # isloate node_modules/ from host, stay in container volume

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
 
volumes:
  dependencies:  ## for isolating container's node_modules/